#   Make file for Turbo Assembler
#   Copyright (c) 1996 by Borland International, Inc.

#       make -B                 Will build the release version
#       make -B -DDEBUG         Will build the debug version

NAME = DEVID
OBJS = DevId.obj ATAId.obj

!if $d(DEBUG)
TASMDEBUG=/zi
LINKDEBUG=/v /s
!else
TASMDEBUG=/m /q /t
LINKDEBUG=/x
!endif


$(NAME).exe: $(OBJS)
  tlink /c $(LINKDEBUG) $(OBJS), $(NAME)
  @if exist *.obj del *.obj
  @if exist *.lst del *.lst
  @if exist *.res del *.res
  @if exist *.tr2 del *.tr2
  @if exist *.td2 del *.td2

.asm.obj:
  tasm /ml $(TASMDEBUG) $&.asm
